title: RSA Metodologias
description: Metodologias y guias de trabajo de la RSA
url: https://redsismicaaustro.github.io
baseurl: /RSA-Metodologias   

# Usa el tema como remote_theme (no uses 'theme:')
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

search_enabled: true
